server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juancamilo11/demo-spring-cloud-config-server-properties
          default-label: main
          clone-on-start: true